//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionScolaire.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Levels
    {
        public Levels()
        {
            this.Pupils = new HashSet<Pupils>();
        }
    
        public System.Guid Id { get; set; }
        public string Title { get; set; }
        public System.Guid Cycle_Id { get; set; }
    
        public virtual Cycles Cycles { get; set; }
        public virtual ICollection<Pupils> Pupils { get; set; }
    }
}
