//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionScolaire.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pupils
    {
        public Pupils()
        {
            this.Results = new HashSet<Results>();
        }
    
        public System.Guid Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public short Sex { get; set; }
        public System.DateTime BirthdayDate { get; set; }
        public short State { get; set; }
        public System.Guid Tutor_Id { get; set; }
        public System.Guid Classroom_Id { get; set; }
        public System.Guid Level_Id { get; set; }
    
        public virtual Classrooms Classrooms { get; set; }
        public virtual Levels Levels { get; set; }
        public virtual Tutors Tutors { get; set; }
        public virtual ICollection<Results> Results { get; set; }
    }
}
