//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionScolaire.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.Classrooms = new HashSet<Classrooms>();
            this.Establishments = new HashSet<Establishments>();
            this.Evaluations = new HashSet<Evaluations>();
        }
    
        public System.Guid Id { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Mail { get; set; }
    
        public virtual ICollection<Classrooms> Classrooms { get; set; }
        public virtual ICollection<Establishments> Establishments { get; set; }
        public virtual ICollection<Evaluations> Evaluations { get; set; }
    }
}
