//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionScolaire.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Years
    {
        public Years()
        {
            this.Classrooms = new HashSet<Classrooms>();
            this.Periods = new HashSet<Periods>();
        }
    
        public System.Guid Id { get; set; }
        public int Year { get; set; }
    
        public virtual ICollection<Classrooms> Classrooms { get; set; }
        public virtual ICollection<Periods> Periods { get; set; }
    }
}
